### ISSUE TITLE
question about the label

### ISSUE THREAD

**Issue by yuzehui1996** [ronghuaiyang/arcface-pytorch#12]
hey, when I run the training epoch 0, the error is below:

/pytorch/aten/src/THC/THCTensorScatterGather.cu:176: void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [0,0,0], thread: [49,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    loss = criterion(output, label)
  File "/home/pris/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pris/yzh/arcface-pytorch/models/focal_loss.py", line 27, in forward
    loss = loss.mean()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317

I quite appriciate for your help!
I only changed the input size to (3,112,112) and change the fc5 input_features;
And I set the batch_size = 64, the same as test_batch_size.

**Comment by yuzehui1996** [comment]
BTW, the epoch 0 has been trained for a period of time, and it showed the error above suddenly.

**Comment by ronghuaiyang** [comment]
it looks like the images in your dataset have different size
