### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by Vermeille** [ronghuaiyang/arcface-pytorch#15]
Hi!

What's the license of this code? I'd like to make drastic changes to this codebase and use it in my company.

Many thanks :)

**Comment by ronghuaiyang** [comment]
just use it.

**Comment by Vermeille** [comment]
Thank you very much :)

**Comment by Belial-public** [comment]
Sorry to bother you, but is it possible for you to upload a LICENSE file in the repository?

I understand that you stated above that it's ok to use the codebase, but for legal reasons it's advisable to have it specified in a license file.

Thanks in advance
