### ISSUE TITLE
What is purpose of easymargin?

### ISSUE THREAD

**Issue by lzj322** [ronghuaiyang/arcface-pytorch#2]
I didn't see any clues in authors' paper about easy margin in ArcMarginProduct. What is this for? And why replace cosine when cosine greater than zero?

**Comment by ronghuaiyang** [comment]
the easy margin is implemented in https://github.com/deepinsight/insightface, the purpose of the easy margin is not to consider the theta + m > pi. we need to replace theta with theta + m when theta + m < pi, so we replace cosine when cosine greater than zero

**Comment by felixfuu** [comment]
@ronghuaiyang   can you share your eval accuracy on LFW and YTF?

**Comment by ronghuaiyang** [comment]
@felixfuu, I only test the model on LFW，the accuracy is about 99.3%.

**Comment by yxchng** [comment]
@ronghuaiyang i notice that the replacement is either cosine theta or sin(pi-m)*m. Any reason for such replacement? the function will no longer be monotonically decreasing after the replacement?

**Comment by JoyLuo** [comment]
> @ronghuaiyang i notice that the replacement is either cosine theta or sin(pi-m)*m. Any reason for such replacement? the function will no longer be monotonically decreasing after the replacement?

I also confused in the reason of cosine - self.mm when theta + m >=180 degree. the cosine - self.mm is monotonicall because the mm is constant when self.mm = math.sin(math.pi - m)*m.
