### ISSUE TITLE
weight update

### ISSUE THREAD

**Issue by jaideep11061982** [ronghuaiyang/arcface-pytorch#20]
hi rong.. thanks for providing this implementation...
i have got basic question
 torch.optim.Adam([{'params': model.parameters()}, {'params': metric_fc.parameters()}],
                                     lr=opt.lr, weight_decay=opt.weight_decay)
why do we need this to list the param...
I thought using nn.Param() would register the newly added parameter and there after weights should get autoupdated at the end of epoch.

**Comment by ronghuaiyang** [comment]
the optimizer need to know which parameters shoud be update，you could update all of them or update part of them.
