### ISSUE TITLE
What is the lfw_test_list used for

### ISSUE THREAD

**Issue by liquor233** [ronghuaiyang/arcface-pytorch#21]
Hi, thank you for your great repo.
I am new in machine learning and I am concerned why should I use a lfw_test_pair.txt? can I just use the whole LFW datasets to test my model?

**Comment by ronghuaiyang** [comment]
the lfw_test_pair.txt contains 6000 pairs of face images, 3000 positive, 3000 negitive, it's a stander benchmark.  If you want to use the whole LFW datasets to test your model, you need to construct your own test pairs.

**Comment by liquor233** [comment]
Now I understand, thank you very much! 
Besides that, I am also curious that where you downloaded this benchmark. I found pair.txt on the lfw website, but I noticed that they are different, did you generate this file by yourself?

**Comment by ronghuaiyang** [comment]
> Now I understand, thank you very much!
> Besides that, I am also curious that where you downloaded this benchmark. I found pair.txt on the lfw website, but I noticed that they are different, did you generate this file by yourself?

yes, i generate myself
