### ISSUE TITLE
pretrained model and dataset

### ISSUE THREAD

**Issue by CherylZR** [ronghuaiyang/arcface-pytorch#3]
Hi,
Thank you for sharing your code. It's awesome. What's your dataset for training and could you please share the pretrained model?

**Comment by ronghuaiyang** [comment]
@CherylZR I just upload the pretrianed model and the lfw test dataset. The dataset i used for training is webface.

**Comment by tengerye** [comment]
Hi, I noticed there are gray images in webface. May I know how did you process that? Did you just copy the values to the three channel?
