### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset'

### ISSUE THREAD

**Issue by 2151330** [ronghuaiyang/arcface-pytorch#33]
Is the relevant document of your project complete?
 When I run train.py, the following problem appears. And I don't know what dataset.py does,Can you tell me? Thanks a lot.
![image](https://user-images.githubusercontent.com/41284417/61171890-575c3a80-a5b0-11e9-9688-da5ccd9249a3.png)
The files in the following paths don't exist in dataset.py.
![image](https://user-images.githubusercontent.com/41284417/61171938-e1a49e80-a5b0-11e9-9bf0-f46847f9e5b7.png)

**Comment by 15380831711** [comment]
`__init__.py 模块名前加个点，如：`
`from .dataset import Dataset`
