### ISSUE TITLE
config配置

### ISSUE THREAD

**Issue by meiyoumimazaban** [ronghuaiyang/arcface-pytorch#37]
train_root = '/data/Datasets/webface/CASIA-maxpy-clean-crop-144/'
    train_list = '/data/Datasets/webface/train_data_13938.txt'
    val_list = '/data/Datasets/webface/val_data_13938.txt'

    test_root = '/data1/Datasets/anti-spoofing/test/data_align_256'
    test_list = 'test.txt'
这些文件夹在哪，训练不了

**Comment by zhuvensi** [comment]
> train_root = '/data/Datasets/webface/CASIA-maxpy-clean-crop-144/' train_list = '/data/Datasets/webface/train_data_13938.txt' val_list = '/data/Datasets/webface/val_data_13938.txt'
> 
> ```
> test_root = '/data1/Datasets/anti-spoofing/test/data_align_256'
> test_list = 'test.txt'
> ```
> 
> 这些文件夹在哪，训练不了

你好啊，解决了吗，想问一下
