### ISSUE TITLE
the CASIA-webface-dataset and the train-validation list

### ISSUE THREAD

**Issue by ShiinaMitsuki** [ronghuaiyang/arcface-pytorch#5]
Hi, thanks a lot for the pytorch implementation of the arcface! 
I'm trying to train the model using your code, but I find no where to download the webface dataset, It's homepage is missing.
I'd be appreciate if be told where to download the 'CASIA-maxpy-clean-crop-144' dataset and the train-validation split list.

Thks in advance!!

**Comment by ronghuaiyang** [comment]
@ShiinaMitsuki I'm sorrry I can't share the dataset with you. You can use other dataset instead. The VGGFace is also public.
http://www.robots.ox.ac.uk/~vgg/software/vgg_face/

**Comment by lizhenstat** [comment]
@ronghuaiyang  Hi, same questions here, I have already downloaded CASIA-webface-clean from another repo. Can you share the "train_data_13938.txt" and "val_data_13938.txt" in this repo?

Thanks a lot!

**Comment by AmmarKhawer** [comment]
@lizhenstat @ronghuaiyang Hi, Can you share the "train_data_13938.txt" and "val_data_13938.txt" in this repo with me too?

**Comment by abcde-bit** [comment]
> @lizhenstat @ronghuaiyang Hi, Can you share the "train_data_13938.txt" and "val_data_13938.txt" in this repo with me too?

Hi,brother .How did you get the "train_data_13938.txt" and "val_data_13938.txt" finally?

**Comment by lizhenstat** [comment]
@abcde-bit @AmmarKhawer Hi, I did not find "train_data_13938.txt" and "val_data_13938.txt" at last, I used https://github.com/ronghuaiyang/arcface-pytorch/issues/62#issuecomment-899155326 instead.

**Comment by abcde-bit** [comment]
> @abcde-bit @AmmarKhawer Hi, I did not find "train_data_13938.txt" and "val_data_13938.txt" at last, I used [#62 (comment)](https://github.com/ronghuaiyang/arcface-pytorch/issues/62#issuecomment-899155326) instead.

Thank you very much! I'm trying to do it the way you do.
