### ISSUE TITLE
0 accuracy

### ISSUE THREAD

**Issue by cy69855522** [ronghuaiyang/arcface-pytorch#6]
I always get 0 accuracy using Arcface loss and Cross Entropy loss.(loss decrease normally)

**Comment by cy69855522** [comment]
> I always get 0 accuracy using Arcface loss and Cross Entropy loss.(loss decrease normally)

**Comment by CaptainEven** [comment]
@cy69855522 How did u solve this？

**Comment by yonger001** [comment]
@cy69855522 @CaptainEven Hi，Have u solved this problem？Now，I meet with the same one，after several epoch，the acc is still 0.0, but the loss decreases normally.

**Comment by CaptainEven** [comment]
@yonger001 I 'v solved. acc = np.mean((output == label).astype(float))

**Comment by cy69855522** [comment]
> @cy69855522 @CaptainEven Hi，Have u solved this problem？Now，I meet with the same one，after several epoch，the acc is still 0.0, but the loss decreases normally.

╮(╯▽╰)╭ No, I haven't. I use cosface‘s loss function to replace.

**Comment by yonger001** [comment]
@CaptainEven ok, thanks. I will continue to check. BTW,in your training process,How do u set these parameters(bs, lr, epoch, m, s)?  and what's ur acc ?

**Comment by CaptainEven** [comment]
@yonger001 
    for epoch_i in range(opt.max_epoch):
        scheduler.step()
        print('=> learning rate: ', scheduler.get_lr()[0])

        model.train()
        metric_fc.train()

        for batch_i, data in enumerate(train_loader):
            data_input, label = data
            data_input, label = data_input.to(device), label.to(device).long()

            # extract feature vector
            feature = model.forward(data_input)

            # output classification result
            output = metric_fc.forward(feature, label)

            loss = loss_func(output, label)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            iter_count = epoch_i * len(train_loader) + batch_i

            if iter_count % opt.print_freq == 0:
                output = output.data.cpu().numpy()
                output = np.argmax(output, axis=1)
                label = label.data.cpu().numpy()

                acc = np.mean((output == label).astype(float))

                print('=> train epoch {} iter {:>4d}/{:>4d}'
                      ', total_iter {:>5d} '
                      '| loss {:.3f} '
                      '| accuracy {:.2%}'
                      .format(epoch_i,
                              batch_i,
                              len(train_loader),
                              iter_count,
                              loss.item(),
                              acc))

                if opt.display:
                    visualizer.display_current_results(
                        iter_count, loss.item(), name='train_loss')
                    visualizer.display_current_results(
                        iter_count, acc, name='train_acc')

**Comment by yonger001** [comment]
@CaptainEven 3Q for ur reply, maybe u don't follow me, I want to compare ur parameters with my pa,but this code u provided don't contain these parameters.

**Comment by ReverseSystem001** [comment]
Traceback (most recent call last):
File "train.py", line 189, in train
loss.backward()
File "/usr/lib64/python3.6/site-packages/torch/tensor.py", line 107, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/usr/lib64/python3.6/site-packages/torch/autograd/init.py", line 93, in backward
allow_unreachable=True) # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
to solve this problem, i add a line code in the train.py.
178 loss = criterion(output, label)
180 loss.requires_grad = True
and then it do not report errors. but when i train, the loss is not decline, and the acc is always zero

hope your replay

**Comment by ponykid** [comment]
I face the same problem， the acc is zero， but the loss decreases normaly

**Comment by ponykid** [comment]
> 
could you tell me how solve the question？
