### ISSUE TITLE
关于训练速度慢的问题

### ISSUE THREAD

**Issue by hzq-zjm** [ronghuaiyang/arcface-pytorch#67]
各位好，我在训练resnet_face18，batch_size = 128 。发现一次迭代耗时居然要5s左右。定位到 __getitem__()里面的Image.open()加载图片非常慢，一张耗时120ms左右，不知道大家有没有碰到这种情况。

**Comment by ingale726** [comment]
你解决了吗?

**Comment by hzq-zjm** [comment]
服务器原因
