### ISSUE TITLE
The pre-trained model download link is broken

### ISSUE THREAD

**Issue by x7177214** [ronghuaiyang/arcface-pytorch#7]
Hi, the pre-trained model download link is broken, could you plead fix it?

Thansks.

**Comment by ronghuaiyang** [comment]
@x7177214 I checked the link, it's not broken, you can try it again.

**Comment by x7177214** [comment]
Thank for your reply. But when I click the link you provide (https://pan.baidu.com/s/1TgGLBjGASo5hoQ3Mc__WIQ)

it directs to https://pan.baidu.com/error/404.html which shows "the page you visit doesn't exist" message.

**Comment by x7177214** [comment]
OK, I can download now. Thanks.
