### ISSUE TITLE
Pretrained model is not contained in the link 

### ISSUE THREAD

**Issue by Icegreenlhd** [ronghuaiyang/arcface-pytorch#84]
When I open the pretrained model and lfw datasets **link**, I only find the dataset but not the pretrained model.
Where is the pretrained model? If I miss the file, please point out. Thanks very much.

**Comment by Awenjie10** [comment]
> When I open the pretrained model and lfw datasets **link**, I only find the dataset but not the pretrained model.
> Where is the pretrained model? If I miss the file, please point out. Thanks very much.

You could try to download the model from google driver link: https://drive.google.com/drive/folders/14WeZV0o-oMax1p8soUZhezPliqUVp0gD?usp=sharing.

**Comment by Icegreenlhd** [comment]
Thanks a lot. Problem solved.
